package com.wxg.bean.copy;

import java.util.Date;

public class Member {
    private String id;

    private String userId;

    private String orgId;

    private String name;

    private String title;

   

	private Byte status;

    private Byte role;

    private String creatorId;

    private Date createTime;

    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_id
     *
     * @return the value of member.user_id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_id
     *
     * @param userId the value for member.user_id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.org_id
     *
     * @return the value of member.org_id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.org_id
     *
     * @param orgId the value for member.org_id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.title
     *
     * @return the value of member.title
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.title
     *
     * @param title the value for member.title
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.role
     *
     * @return the value of member.role
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public Byte getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.role
     *
     * @param role the value for member.role
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setRole(Byte role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.creator_id
     *
     * @return the value of member.creator_id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.creator_id
     *
     * @param creatorId the value for member.creator_id
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_time
     *
     * @return the value of member.create_time
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_time
     *
     * @param createTime the value for member.create_time
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.deleted
     *
     * @return the value of member.deleted
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.deleted
     *
     * @param deleted the value for member.deleted
     *
     * @mbggenerated Fri Feb 17 11:07:14 CST 2017
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public Member(String id, String userId, String orgId, String name, String title, Byte status, Byte role,
			String creatorId, Date createTime, Boolean deleted) {
		super();
		this.id = id;
		this.userId = userId;
		this.orgId = orgId;
		this.name = name;
		this.title = title;
		this.status = status;
		this.role = role;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.deleted = deleted;
	}
}